name: pr-check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - run: yarn
      - run: yarn build
      - run: yarn test:ci-coverage
