name: pr-check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: Borales/actions-yarn@v5.0.0
        with:
          cmd: install

      - name: Build library
        uses: Borales/actions-yarn@v5.0.0
        with:
          cmd: build

      - name: Test library
        uses: Borales/actions-yarn@v5.0.0
        with:
          cmd: test:ci-coverage
