name: pr-check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          cmd: install
      - name: Build library
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          cmd: build
      - name: Test library
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          cmd: test:ci-coverage
