name: pr-check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        shell: bash
        working-directory: ${{ inputs.cwd }}
        run: yarn
      - name: Build library
        shell: bash
        working-directory: ${{ inputs.cwd }}
        run: yarn build
      - name: Test library
        shell: bash
        working-directory: ${{ inputs.cwd }}
        run: yarn test:ci-coverage
